using System;
using System.Collections.Generic;

namespace TKProcessor.Models.SHR
{
    public partial class Personnel
    {
        public string CompanyNum { get; set; }
        public string EmployeeNum { get; set; }
        public string PictureFile { get; set; }
        public string Title { get; set; }
        public string Surname { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string PreferredName { get; set; }
        public string Initials { get; set; }
        public string EmailAddress { get; set; }
        public DateTime? BirthDate { get; set; }
        public string Sex { get; set; }
        public string Idnum { get; set; }
        public string EthnicGroup { get; set; }
        public string Nationality { get; set; }
        public string Language { get; set; }
        public bool? Write { get; set; }
        public bool? Read { get; set; }
        public string MaritialStatus { get; set; }
        public string SpouseName { get; set; }
        public string SpouseTel { get; set; }
        public string Religion { get; set; }
        public string HomeTel { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Address4 { get; set; }
        public string Pobox { get; set; }
        public string Poarea { get; set; }
        public string Pocode { get; set; }
        public string Worktel { get; set; }
        public string CellTel { get; set; }
        public string Bank { get; set; }
        public string Branch { get; set; }
        public string AccNum { get; set; }
        public string AccName { get; set; }
        public DateTime? Appointdate { get; set; }
        public string Appointype { get; set; }
        public bool? Induction { get; set; }
        public double? RecruitCost { get; set; }
        public string JobTitle { get; set; }
        public string JobGrade { get; set; }
        public string DeptName { get; set; }
        public string Uifnum { get; set; }
        public string ClockNumber { get; set; }
        public string Payenum { get; set; }
        public string TaxCode { get; set; }
        public string TaxNum { get; set; }
        public string TaxOffice { get; set; }
        public string PayPoint { get; set; }
        public string PayMode { get; set; }
        public string BankCode { get; set; }
        public short? TaxDependants { get; set; }
        public DateTime? TerminationDate { get; set; }
        public bool? Termination { get; set; }
        public string TerminationReason { get; set; }
        public string CostCentre { get; set; }
        public string LeaveScheme { get; set; }
        public string SkillLevel { get; set; }
        public string OfficeNo { get; set; }
        public string ExtensionNo { get; set; }
        public bool? Hr { get; set; }
        public DateTime? DateJoinedGroup { get; set; }
        public string NoticePeriod { get; set; }
        public string ReligionNotes { get; set; }
        public string Flag { get; set; }
        public int? Resigned { get; set; }
        public byte? Recruit { get; set; }
        public string RecruitStatus { get; set; }
        public string PayrollEmployeeNum { get; set; }
        public string StreetState { get; set; }
        public string Postate { get; set; }
        public string Esspath { get; set; }
        public string EmploymentType { get; set; }
        public string Disability { get; set; }
        public string DisabilityNotes { get; set; }
        public byte[] EmployeePicture { get; set; }
        public long? TotalEarnedLeaves { get; set; }
        public long? LeavesForEncashment { get; set; }
        public string DpPayrollCode { get; set; }
        public string DpAttributeCode { get; set; }
        public DateTime? Payday { get; set; }
        public string Province { get; set; }
        public decimal? Latitude { get; set; }
        public decimal? Longitude { get; set; }
        public string PayrollNumber { get; set; }
        public string AddrUnit { get; set; }
        public string AddrComplex { get; set; }
        public string AddrStreetNo { get; set; }
        public string AddrStreetName { get; set; }
        public string AddrSuburb { get; set; }
        public string AddrCity { get; set; }
        public string AddrZip { get; set; }
        public string FaxNo { get; set; }
        public string EmailAddress1 { get; set; }
        public string SwiftCode { get; set; }
        public DateTime? EmploymentEndDate { get; set; }
        public string MaidenName { get; set; }
        public int Id { get; set; }
        public string PrivateBag { get; set; }
        public string EmploymentContractType { get; set; }
        public byte? RetirementAge { get; set; }
        public string AddrState { get; set; }
        public string AddrCountryCode { get; set; }
        public long? PathId { get; set; }
        public byte? OutOfficeStatus { get; set; }
        public DateTime? TodateSaved { get; set; }
        public string Tousername { get; set; }
        public string Status { get; set; }
        public DateTime? TransferDate { get; set; }
        public string TransferReason { get; set; }
        public string CountryCode { get; set; }
    }
}
